name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-26.04-arm
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
#      - parallel: #TODO re-enable all parallel lines when https://github.com/actions/runner/issues/4641 is fixed
        - name: Checkout json-builder
          uses: actions/checkout@v6
          with:
            path: builder

        - name: Checkout json-parser
          uses: actions/checkout@v6
          with:
            repository: json-parser/json-parser
            path: parser
            sparse-checkout: |
              json.h
              json.c
            sparse-checkout-cone-mode: false

#      - parallel:
#       - run: c89              -ansi -Wall -Wpedantic -Werror -pedantic -pedantic-errors -D_ANSI_SOURCE -Iparser -Ibuilder -shared parser/json.c builder/json-builder.c -lm -o json-gcc-c89-notrack
#       - run: clang   -std=c89 -ansi -Wall -Wpedantic -Werror -pedantic -pedantic-errors -D_ANSI_SOURCE -Iparser -Ibuilder -shared parser/json.c builder/json-builder.c -lm -o json-gcc-c89-notrack
#       - run: c89              -ansi -Wall -Wpedantic -Werror -pedantic -pedantic-errors -D_ANSI_SOURCE -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared parser/json.c builder/json-builder.c -lm -o json-clang-c89
#       - run: clang   -std=c89 -ansi -Wall -Wpedantic -Werror -pedantic -pedantic-errors -D_ANSI_SOURCE -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared parser/json.c builder/json-builder.c -lm -o json-clang-c89
        - run: gcc     -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors                     -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-c99
        - run: clang   -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors                     -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-c99
        - run: gcc     -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-c99
        - run: clang   -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-c99
        - run: gcc     -std=gnu99     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-gnu99
        - run: clang   -std=gnu99     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-gnu99
        - run: gcc     -std=c11       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-c11
        - run: clang   -std=c11       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-c11
        - run: gcc     -std=c17       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-c17
        - run: clang   -std=c17       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-c17
        - run: gcc     -std=c17       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-c17-unused -Werror=unused-parameter
        - run: clang   -std=c17       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-c17-unused -Werror=unused-parameter
        - run: gcc     -std=c2x       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-c23
        - run: clang   -std=c23       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-c23
        - run: gcc     -std=gnu2x     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-gcc-gnu23
        - run: clang   -std=gnu23     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared                        parser/json.c builder/json-builder.c -lm -o json-clang-gnu23
        - run: g++     -std=c++98     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp98         -Wno-deprecated-declarations
        - run: clang++ -std=c++98     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp98       -Wno-deprecated-declarations
        - run: g++     -std=c++11     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp11         -Wno-deprecated-declarations
        - run: clang++ -std=c++11     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp11       -Wno-deprecated-declarations
        - run: g++     -std=c++14     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp14         -Wno-deprecated-declarations
        - run: clang++ -std=c++14     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp14       -Wno-deprecated-declarations
        - run: g++     -std=c++17     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp17         -Wno-deprecated-declarations
        - run: clang++ -std=c++17     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp17       -Wno-deprecated-declarations
        - run: g++     -std=c++20     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp20         -Wno-deprecated-declarations
        - run: clang++ -std=c++20     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp20       -Wno-deprecated-declarations
        - run: g++     -std=c++23     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp23         -Wno-deprecated-declarations
        - run: clang++ -std=c++23     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp23       -Wno-deprecated-declarations
        - run: g++     -std=c++2b     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-cpp26         -Wno-deprecated-declarations
        - run: clang++ -std=c++26     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp26       -Wno-deprecated-declarations
        - run: g++     -std=gnu++2b   -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-gcc-gnupp26       -Wno-deprecated-declarations
        - run: clang++ -std=gnu++26   -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-gnupp26     -Wno-deprecated-declarations
        - run: clang++ -std=c++2c     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x           c++ parser/json.c builder/json-builder.c -lm -o json-clang-cpp2c       -Wno-deprecated-declarations
        - run: clang   -std=c23       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared       -x objective-c   parser/json.c builder/json-builder.c -lm -o json-clang-objc23      -Wno-deprecated-declarations
        - run: clang   -std=gnu23     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared       -x objective-c   parser/json.c builder/json-builder.c -lm -o json-clang-objgnu23    -Wno-deprecated-declarations
        - run: clang++ -std=c++26     -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x objective-c++ parser/json.c builder/json-builder.c -lm -o json-clang-objcpp26    -Wno-deprecated-declarations
        - run: clang++ -std=gnu++26   -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder -shared -fPIC -x objective-c++ parser/json.c builder/json-builder.c -lm -o json-clang-objgnupp26  -Wno-deprecated-declarations

        - name: Build tests
          run: |
            gcc        -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder parser/json.c builder/json-builder.c builder/test/main.c -lm    -O0          -o json-test-O0
            gcc        -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder parser/json.c builder/json-builder.c builder/test/main.c -lm    -O1 -DNDEBUG -o json-test-O1
            gcc        -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder parser/json.c builder/json-builder.c builder/test/main.c -lm    -O2 -DNDEBUG -o json-test-O2
            gcc        -std=c99       -Wall -Wpedantic -Werror -pedantic -pedantic-errors -DJSON_TRACK_SOURCE -Iparser -Ibuilder parser/json.c builder/json-builder.c builder/test/main.c -lm    -O3 -DNDEBUG -o json-test-O3
            gcc        -std=c99                                                           -DJSON_TRACK_SOURCE -Iparser -Ibuilder parser/json.c builder/json-builder.c builder/test/main.c -lm -g -O0 -fno-omit-frame-pointer -fsanitize=address   -o json-test-sanitize-address
            gcc        -std=c99                                                           -DJSON_TRACK_SOURCE -Iparser -Ibuilder parser/json.c builder/json-builder.c builder/test/main.c -lm -g -O0 -fno-omit-frame-pointer -fsanitize=undefined -o json-test-sanitize-undefined

#      - parallel:
        - name: Run json-test-O0
          run: |
            cd builder/test
            ../../json-test-O0

        - name: Run json-test-O1
          run: |
            cd builder/test
            ../../json-test-O1

        - name: Run json-test-O2
          run: |
            cd builder/test
            ../../json-test-O2

        - name: Run json-test-O3
          run: |
            cd builder/test
            ../../json-test-O3

        - name: Run json-test-sanitize-address
          run: |
            cd builder/test
            ../../json-test-sanitize-address

        - name: Run json-test-sanitize-undefined
          run: |
            cd builder/test
            ../../json-test-sanitize-undefined

  windows:
    permissions:
      contents: read
    strategy:
      matrix:
        hostarch:
          - x64
          - arm64
        targarch:
          - x86
          - x64
#         - arm # disabled because newer ARM processors and Windows 11 24H2 both removed ARM32 support
          - arm64
        include:
          - hostarch: x86 #TODO only used for the x86 asan run due to the DLL situation described below
            targarch: x86
    runs-on: ${{ case(matrix.hostarch == 'arm64', 'windows-11-vs2026-arm', 'windows-latest') }}
    steps:
#      - parallel:
        - name: Checkout json-builder
          uses: actions/checkout@v6
          with:
            path: builder

        - name: Checkout json-parser
          uses: actions/checkout@v6
          with:
            repository: json-parser/json-parser
            path: parser
            sparse-checkout: |
              json.h
              json.c
            sparse-checkout-cone-mode: false

        - name: Add cl.exe to path
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: ${{ case(matrix.hostarch == matrix.targarch, matrix.hostarch, format('{0}_{1}', matrix.hostarch, matrix.targarch)) }}

        - name: Make directories for parallel builds
          run: |
            mkdir p-c89-msvc-cl
            mkdir p-c89-clangcl
            mkdir b-c89-msvc-cl
            mkdir b-c89-clangcl
            mkdir b-c11-msvc-cl
            mkdir b-c11-clangcl
            mkdir b-c17-msvc-cl
            mkdir b-c17-clangcl
            mkdir b-clt-msvc-cl
            mkdir b-clt-clangcl
            mkdir b-x14-msvc-cl
            mkdir b-x14-clangcl
            mkdir b-x17-msvc-cl
            mkdir b-x17-clangcl
            mkdir b-x20-msvc-cl
            mkdir b-x20-clangcl
            mkdir b-xlt-msvc-cl
            mkdir b-xlt-clangcl
            mkdir t-xlt-msvc-cl
            mkdir t-xlt-clangcl
            mkdir a-xlt-msvc-cl
            mkdir e-xlt-msvc-cl

#      - parallel:
        - run:       cl /Fop-c89-msvc-cl\ /Fep-c89-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /Za                            /Wall                     /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run: clang-cl /Fop-c89-clangcl\ /Fep-c89-clangcl\ /permissive- /c                               /volatile:iso /utf-8                                /Wall                     /I parser /I builder /LD     parser/json.c     builder/json-builder.c 
        - run:       cl /Fob-c89-msvc-cl\ /Feb-c89-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /Za                            /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run: clang-cl /Fob-c89-clangcl\ /Feb-c89-clangcl\ /permissive- /c                               /volatile:iso /utf-8                                /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run:       cl /Fob-c11-msvc-cl\ /Feb-c11-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c11                       /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run: clang-cl /Fob-c11-clangcl\ /Feb-c11-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:c11                       /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run:       cl /Fob-c17-msvc-cl\ /Feb-c17-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c17                       /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run: clang-cl /Fob-c17-clangcl\ /Feb-c17-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:c17                       /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run:       cl /Fob-clt-msvc-cl\ /Feb-clt-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:clatest                   /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run: clang-cl /Fob-clt-clangcl\ /Feb-clt-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:clatest                   /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD     parser/json.c     builder/json-builder.c
        - run:       cl /Fob-x14-msvc-cl\ /Feb-x14-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++14     /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run: clang-cl /Fob-x14-clangcl\ /Feb-x14-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:c++14     /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run:       cl /Fob-x17-msvc-cl\ /Feb-x17-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++17     /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run: clang-cl /Fob-x17-clangcl\ /Feb-x17-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:c++17     /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run:       cl /Fob-x20-msvc-cl\ /Feb-x20-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++20     /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run: clang-cl /Fob-x20-clangcl\ /Feb-x20-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:c++20     /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run:       cl /Fob-xlt-msvc-cl\ /Feb-xlt-msvc-cl\ /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++latest /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c
        - run: clang-cl /Fob-xlt-clangcl\ /Feb-xlt-clangcl\ /permissive- /c                               /volatile:iso /utf-8 /std:c++latest /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /LD /Tp parser/json.c /Tp builder/json-builder.c

        - name: Build ARM64X DLL
          if: matrix.targarch == 'arm64'
          run: |
            mkdir x-arm64
            mkdir x-arm64ec
            cl          /Fox-arm64\       /c                /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8                                      /DJSON_TRACK_SOURCE /I parser /I builder         parser/json.c     builder/json-builder.c
            cl /arm64EC /Fox-arm64ec\     /c                /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8                                      /DJSON_TRACK_SOURCE /I parser /I builder         parser/json.c     builder/json-builder.c
            link /DLL /MACHINE:ARM64X softintrin.lib x-arm64ec\json.obj x-arm64ec\json-builder.obj x-arm64\json.obj x-arm64\json-builder.obj /out:json-arm64x.dll

        - name: Build tests
          run:       cl /Fot-xlt-msvc-cl\                   /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++latest /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /MT  /Tp parser/json.c /Tp builder/json-builder.c /Tp builder\test\main.c /Febuilder\test\json-test.exe

        - name: Build tests (ClangCL)
          if: matrix.hostarch == matrix.targarch && matrix.hostarch != 'x64' && matrix.hostarch != 'x86' #TODO why does clang break just right here when not crosscompiling on x86/x64 but works fine everywhere else?
          run: clang-cl /Fot-xlt-clangcl\                   /permissive-                                  /volatile:iso /utf-8 /std:c++latest /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /MT  /Tp parser/json.c /Tp builder/json-builder.c /Tp builder\test\main.c /Febuilder\test\json-test-clangcl.exe

        - name: Build tests with asan
          run:       cl /Foa-xlt-msvc-cl\                   /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++latest /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /MTd /Tp parser/json.c /Tp builder/json-builder.c /Tp builder\test\main.c /Zi /fsanitize=address /Febuilder\test\json-test-asan.exe

        - name: Build ARM64EC tests
          if: matrix.targarch == 'arm64'
          run:       cl /Foe-xlt-msvc-cl\                   /permissive- /Zc:preprocessor /Zc:throwingNew /volatile:iso /utf-8 /std:c++latest /Zc:__cplusplus /Wall /DJSON_TRACK_SOURCE /I parser /I builder /MT  /Tp parser/json.c /Tp builder/json-builder.c /Tp builder\test\main.c /arm64EC /Febuilder\test\json-test-arm64ec.exe

#      - parallel:
        - name: Run tests
          if: matrix.hostarch == 'arm64' || !contains(matrix.targarch, 'arm')
          working-directory: ./builder/test
          run: ./json-test.exe

        - name: Run tests (ClangCL)
          if: (matrix.hostarch == 'arm64' || !contains(matrix.targarch, 'arm')) && matrix.hostarch == matrix.targarch && matrix.hostarch != 'x64' && matrix.hostarch != 'x86' #TODO
          working-directory: ./builder/test
          run: ./json-test-clangcl.exe

        - name: Run tests with asan
          if: (matrix.hostarch == 'arm64' || !contains(matrix.targarch, 'arm')) && matrix.hostarch == matrix.targarch #TODO need proper handling of asan DLLs for mismatched host+targ https://devblogs.microsoft.com/cppblog/msvc-address-sanitizer-one-dll-for-all-runtime-configurations/#troubleshooting
          working-directory: ./builder/test
          run: ./json-test-asan.exe

        - name: Run ARM64EC tests
          if: matrix.hostarch == 'arm64' && matrix.targarch == 'arm64'
          working-directory: ./builder/test
          run: ./json-test-arm64ec.exe
